In [1]:
import pandas as pd

df = pd.read_csv('C:/Users/ethan/Downloads/archive/one_dollar_spin_and_go.csv', parse_dates=[['date', 'time']])
df

,date_time,buyin,tourn_id,table,hand_id,table_size,level,playing,seat,names,...,pot_turn,pot_river,ante,blinds,bet_pre,bet_flop,bet_turn,bet_river,result,balance
0,2020-06-07 18:15:09,$0.92+$0.08,2929450288,1,215051507105,3,1,3,1,fa538846,...,30,30,0,0,0,0,0,0,gave up,0
1,2020-06-07 18:15:09,$0.92+$0.08,2929450288,1,215051507105,3,1,3,2,676c5599,...,30,30,0,10,10,0,0,0,gave up,-10
2,2020-06-07 18:15:09,$0.92+$0.08,2929450288,1,215051507105,3,1,3,3,7055f691,...,30,30,0,20,20,0,0,0,took chips,10
3,2020-06-07 18:15:23,$0.92+$0.08,2929450288,1,215051520234,3,1,3,1,fa538846,...,180,180,0,20,60,60,0,0,took chips,60
4,2020-06-07 18:15:23,$0.92+$0.08,2929450288,1,215051520234,3,1,3,2,676c5599,...,180,180,0,0,0,0,0,0,gave up,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102610,2021-03-30 19:00:02,$0.92+$0.08,3162349514,1,225348760558,3,1,3,2,c98315f0,...,560,560,0,10,500,0,0,0,took chips,60
102611,2021-03-30 19:00:02,$0.92+$0.08,3162349514,1,225348760558,3,1,3,3,e6bfd5eb,...,560,560,0,20,20,0,0,0,gave up,-20
102612,2021-03-30 19:00:25,$0.92+$0.08,3162349514,1,225348768503,3,1,3,1,fa538846,...,1030,1030,0,20,20,50,390,0,lost,-460
102613,2021-03-30 19:00:25,$0.92+$0.08,3162349514,1,225348768503,3,1,3,2,c98315f0,...,1030,1030,0,0,20,50,490,0,won,470
102614,2021-03-30 19:00:25,$0.92+$0.08,3162349514,1,225348768503,3,1,3,3,e6bfd5eb,...,1030,1030,0,10,10,0,0,0,gave up,-10

In [2]:
df = df.rename(columns={
    'date_time' : 'DateTime', 
    'hand_id' : 'HandID', 
    'names' : 'UserID',
    'blinds' : 'blinds_level',
    'stack' : 'init_stack',
})

In [ ]:
df.to_csv('../data/kaggle_ds.csv')
from gcp_csv_import_format import format_df_to_csv
format_df_to_csv(
    df,
    ['HandID', 'UserID'],
    ['HandID','UserID','DateTime','buyin','blinds_level','init_stack','position','action_pre','action_flop','action_turn','action_river','all_in','cards','board_flop','board_turn','board_river','pot_pre','pot_flop','pot_turn','pot_river','ante','bet_pre','bet_flop','bet_turn','bet_river','result','balance'],
    '../data/gamehistory_k.csv'
)